"use strict";

/**
 * Central store – single source of truth for `state` and `el` registry.
 * Loaded before app.js. App.js delegates via `window.piStore`.
 * Fallback path in app.js keeps tests working without DOM.
 */

(function exposeStore(root) {
  const $ = (sel) => document.querySelector(sel);

  // Element registry – mirrors the original `const el = { ... }` in app.js
  // Query is deferred: if DOM not yet ready, entries resolve to null and
  // app.js fallback will re-query. Store is loaded at end of <body> so DOM is ready.
  const el = {
    main: $("#main"),
    sidebar: $("#sidebar"),
    projectsList: $("#projects-list"),
    sessionSearch: $("#session-search"),
    addProject: $("#btn-add-project"),
    sessionsCount: $("#sessions-count"),
    newChat: $("#btn-new-chat"),
    topNewChat: $("#top-new-chat"),
    commandsBtn: $("#btn-commands"),
    treeBtn: $("#btn-tree"),
    sessionToolsBtn: $("#btn-session-tools"),
    toggleSidebar: $("#btn-toggle-sidebar"),
    chatTabs: $("#chat-tabs"),
    themeBtn: $("#btn-theme"),
    chat: $("#chat"),
    messages: $("#messages"),
    emptyState: $("#empty-state"),
    emptyHint: $("#empty-hint"),
    input: $("#input"),
    slashSuggestions: $("#slash-suggestions"),
    atSuggestions: $("#at-suggestions"),
    attachmentTray: $("#attachment-tray"),
    attachBtn: $("#btn-attach"),
    attachImageBtn: $("#btn-attach-image"),
    composerWrap: $("#composer-wrap"),
    composerActions: document.querySelector(".composer-actions"),
    modelDock: $("#model-dock"),
    sendGroup: document.querySelector(".send-group"),
    sendBtn: $("#btn-send"),
    stopBtn: $("#btn-stop"),
    queuedNote: $("#queued-note"),
    busySendChoice: $("#busy-send-choice"),
    queueBehaviorButtons: document.querySelectorAll("[data-queue-behavior]"),
    extensionStatuses: $("#extension-statuses"),
    extensionWidgetsAbove: $("#extension-widgets-above"),
    extensionWidgetsBelow: $("#extension-widgets-below"),
    statusCwd: $("#status-cwd"),
    statusActivity: $("#status-activity"),
    statusTokens: $("#status-tokens"),
    modelBtn: $("#model-btn"),
    modelLabel: $("#model-label"),
    modelMenu: $("#model-menu"),
    modelSearch: $("#model-search"),
    modelList: $("#model-list"),
    providerBtn: $("#provider-btn"),
    providerLabel: $("#provider-label"),
    providerMenu: $("#provider-menu"),
    providerList: $("#provider-list"),
    thinkingBtn: $("#thinking-btn"),
    thinkingLabel: $("#thinking-label"),
    thinkingMenu: $("#thinking-menu"),
    thinkingList: $("#thinking-list"),
    thinkingDropdown: $("#thinking-dropdown"),
    piChip: $("#pi-chip"),
    piChipText: $("#pi-chip-text"),
    modalPi: $("#modal-pi"),
    piStatusBox: $("#pi-status-box"),
    btnPiInstall: $("#btn-pi-install"),
    btnPiUpdate: $("#btn-pi-update"),
    btnPiRecheck: $("#btn-pi-recheck"),
    btnPiClose: $("#btn-pi-close"),
    maintenanceLog: $("#maintenance-log"),
    modalSettings: $("#modal-settings"),
    settingCwd: $("#setting-cwd"),
    btnPickCwd: $("#btn-pick-cwd"),
    settingPiPath: $("#setting-pipath"),
    settingSessionsDir: $("#setting-sessionsdir"),
    settingLanguage: $("#setting-language"),
    btnSettingsSave: $("#btn-settings-save"),
    btnSettingsClose: $("#btn-settings-close"),
    btnSettingsOpen: $("#btn-settings"),
    settingsTabs: document.querySelectorAll(".settings-tab"),
    settingsGeneral: $("#settings-general"),
    settingsRuntime: $("#settings-runtime"),
    settingsProviders: $("#settings-providers"),
    projectTrust: $("#setting-project-trust"),
    defaultTrust: $("#setting-default-trust"),
    transport: $("#setting-transport"),
    enabledModels: $("#setting-enabled-models"),
    nativeTools: document.querySelectorAll(".native-tools input[type=checkbox]"),
    shellPath: $("#setting-shell-path"),
    shellPrefix: $("#setting-shell-prefix"),
    compactReserve: $("#setting-compact-reserve"),
    compactKeep: $("#setting-compact-keep"),
    retryMax: $("#setting-retry-max"),
    retryDelay: $("#setting-retry-delay"),
    compactEnabled: $("#setting-compact-enabled"),
    retryEnabled: $("#setting-retry-enabled"),
    imageResize: $("#setting-image-resize"),
    blockImages: $("#setting-block-images"),
    projectTrustNote: $("#project-trust-note"),
    piSettingsSave: $("#btn-pi-settings-save"),
    providerSettingsSearch: $("#provider-settings-search"),
    providerSettingsList: $("#provider-settings-list"),
    packagesBtn: $("#btn-packages"),
    modalPackages: $("#modal-packages"),
    packagesClose: $("#btn-packages-close"),
    packagesDone: $("#btn-packages-done"),
    packagesRefresh: $("#btn-packages-refresh"),
    packageSearch: $("#package-search"),
    packageType: $("#package-type"),
    packageSort: $("#package-sort"),
    packageList: $("#package-list"),
    packagePrev: $("#package-prev"),
    packageNext: $("#package-next"),
    packagePageInfo: $("#package-page-info"),
    packageCatalogLink: $("#package-catalog-link"),
    packageLog: $("#package-log"),
    packageSource: $("#package-source"),
    packageScope: $("#package-scope"),
    packageSourceInstall: $("#btn-package-source-install"),
    packagesUpdate: $("#btn-packages-update"),
    modelsUpdate: $("#btn-models-update"),
    packageInstalledList: $("#package-installed-list"),
    packageInstalledCount: $("#package-installed-count"),
    packageResourceList: $("#package-resource-list"),
    packageResourceCount: $("#package-resource-count"),
    modalUi: $("#modal-ui"),
    uiTitle: $("#ui-title"),
    uiMessage: $("#ui-message"),
    uiOptions: $("#ui-options"),
    uiInputWrap: $("#ui-input-wrap"),
    uiInput: $("#ui-input"),
    uiEditor: $("#ui-editor"),
    uiOk: $("#ui-ok"),
    uiCancel: $("#ui-cancel"),
    modalCommands: $("#modal-commands"),
    commandsClose: $("#btn-commands-close"),
    commandSearch: $("#command-search"),
    commandList: $("#command-list"),
    modalTree: $("#modal-tree"),
    treeClose: $("#btn-tree-close"),
    treeRefresh: $("#btn-tree-refresh"),
    treeList: $("#tree-list"),
    treeSummary: $("#tree-summary"),
    childSession: $("#btn-child-session"),
    cloneSession: $("#btn-clone-session"),
    modalSessionTools: $("#modal-session-tools"),
    sessionToolsClose: $("#btn-session-tools-close"),
    sessionNameInput: $("#session-name-input"),
    sessionRename: $("#btn-session-rename"),
    steeringMode: $("#steering-mode"),
    followUpMode: $("#follow-up-mode"),
    autoCompaction: $("#auto-compaction"),
    autoRetry: $("#auto-retry"),
    compactInstructions: $("#compact-instructions"),
    compactBtn: $("#btn-compact"),
    copyLast: $("#btn-copy-last"),
    exportHtml: $("#btn-export-html"),
    abortRetry: $("#btn-abort-retry"),
    modalAuth: $("#modal-auth"),
    authTitle: $("#auth-title"),
    authSubtitle: $("#auth-subtitle"),
    authStatus: $("#auth-status"),
    authOptions: $("#auth-options"),
    authInputWrap: $("#auth-input-wrap"),
    authInputLabel: $("#auth-input-label"),
    authInput: $("#auth-input"),
    authCancel: $("#btn-auth-cancel"),
    authOk: $("#btn-auth-ok"),
    toasts: $("#toasts"),
    sidebarResizer: $("#sidebar-resizer"),
    chatTooltip: $("#chat-tooltip"),
    btnScrollBottom: $("#btn-scroll-bottom"),
    searchClear: $("#search-clear"),
    globalSearch: document.querySelector(".global-search"),
  };

  const initialCommandUsage = (() => {
    if (root.piPersistence?.loadCommandUsage) {
      try { return root.piPersistence.loadCommandUsage(); } catch {}
    }
    try { return JSON.parse((root.localStorage && root.localStorage.getItem("pi-desktop-command-usage")) || "{}") || {}; }
    catch { return {}; }
  })();

  const state = {
    settings: null,
    sessions: [],
    providers: [],
    attachments: [],
    packages: [],
    installedPackages: [],
    packageResources: [],
    packageBusy: null,
    packagePage: 1,
    packageTotal: 0,
    packagePageSize: 50,
    conversationActive: false,
    expandedProjects: new Set(),
    projectLimits: new Map(),
    openProjectMenu: null,
    activeSessionFile: null,
    activeTabId: null,
    tabs: [],
    tabContexts: new Map(),
    busy: false,
    activeUserMessage: null,
    lastAssistantErrored: false,
    lastAssistantErrorWrap: null,
    retryAttempt: 0,
    streamAssistant: null,
    tools: new Map(),
    modelsCache: null,
    modelsCacheAt: 0,
    currentModel: null,
    thinkingLevels: [],
    steerHintShown: false,
    commands: [],
    commandSelection: 0,
    slashSelection: 0,
    atSelection: 0,
    mentionResults: [],
    mentionQuery: null,
    commandsLoading: null,
    commandUsage: initialCommandUsage,
    autoRetryEnabled: true,
    directBashRunning: false,
    directBashCard: null,
    queueBehavior: "followUp",
    localQueue: [],
    nativeQueue: { steering: [], followUp: [] },
    queuedUserMessages: [],
    dispatchingLocalQueue: false,
    queueDispatchPaused: false,
    stopInProgress: false,
    extensionStatuses: new Map(),
    extensionWidgets: new Map(),
    authFlow: null,
    openingSessionFile: null,
    pendingTabId: null,
    switchGeneration: 0,
    creatingChat: false,
  };

  root.piStore = { el, state, $ };
  if (typeof module !== "undefined" && module.exports) module.exports = { el, state };
})(typeof window !== "undefined" ? window : globalThis);
